apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack
  namespace: monitoring
stringData:
  slack_api_url: "https://hooks.slack.com/services/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"
