apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::343218219945:role/eksctl-gitops-sep-cluster-nodegrou-NodeInstanceRole-RaM77psjFeCP
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::343218219945:user/baksarii
      username: admin
      groups:
        - system:masters
