apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gitops-sep-cluster
  region: ap-northeast-2
  version: "1.29"

managedNodeGroups:
  - name: node-group
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: "C:\\Users\\ohci0\\.ssh\\id_rsa.pub"
