apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-node-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/baksarii/my-nginx-helm-chart.git
    targetRevision: main
    path: charts/my-node
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
