apiVersion: v1
kind: Pod
metadata:
  name: env-test
  namespace: secret-lab
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
