apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-readonly
rules:
    - apiGroups: [""]
      resources: ["pods", "services", "configmaps", "deployments"]
      verbs: ["get", "list", "watch"]