apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata: 
  name: dev-viewer-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: viewer-user
    namespace: dev
roleRef:
  kind: ClusterRole
  name: cluster-readonly
  apiGroup: rbac.authorization.k8s.io